manifest:
  remotes:
   - name: felixm12138
     url-base: https://github.com/felixm12138
  projects:
   - name: zmk
     remote: felixm12138
     revision: main
     import: app/west.yml
  self:
    path: config